import type { Metadata } from 'next';

// Styles
import '@/Styles/globals.css';
import '@/Styles/ckEditor.css'
import '@/Styles/ckContentStyles.css'

// React-Query
import ReactQueryProviders from '@/providers/ReactQueryProvider';
import MuiThemeRegistry from './Styles/MuiThemeRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
          <MuiThemeRegistry>
              <ReactQueryProviders>
                {children}
              </ReactQueryProviders>
          </MuiThemeRegistry>
      </body>
    </html>
  );
}
