import type { Metadata } from 'next';

// Styles
import '@/Styles/globals.css';
import '@/Styles/ckEditor.css'
import '@/Styles/ckContentStyles.css'

// React-Query
import ReactQueryProviders from '@/providers/ReactQueryProvider';
import MuiThemeRegistry from './Styles/MuiThemeRegistry';
import AuthInitializer from '@/providers/AuthInitializer';
import ClientProviders from '@/providers/ClientProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
          <MuiThemeRegistry>
              <ReactQueryProviders>
                <ClientProviders>
                  <AuthInitializer>
                    {children}
                  </AuthInitializer>
                </ClientProviders>
              </ReactQueryProviders>
          </MuiThemeRegistry>
      </body>
    </html>
  );
}
